// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTrack.Data;

#nullable disable

namespace OrderTrack.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241010164801_createDataSEED")]
    partial class createDataSEED
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrderTrack.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descriptions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("names");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "devices and gadgets for everyday use",
                            Name = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "equipment and tools for home improvement",
                            Name = "home appliances"
                        },
                        new
                        {
                            Id = 3,
                            Description = "literature and educational materials",
                            Name = "books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "clothing and accessories",
                            Name = "fashion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "games and entertainment for children",
                            Name = "toys"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
